name: Bug report
about: Reportar problema
title: "[BUG] "
labels: bug
body:
  - type: textarea
    attributes:
      label: Descrição
  - type: textarea
    attributes:
      label: Passos para reproduzir
  - type: textarea
    attributes:
      label: Evidências/logs
